# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HgCli < Formula
  desc ""
  homepage "https://github.com/hostedgraphite/homebrew-hgcli"
  version "0.0.2"

  on_macos do
    url "https://github.com/hostedgraphite/hg-cli/releases/download/v0.0.2/hg-cli_0.0.2_darwin_all.tar.gz"
    sha256 "1291761d84c9ac11a969b5e7679a7cf2c5314a01dd31bfcb728db312467942ef"

    def install
      bin.install "hg-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hostedgraphite/hg-cli/releases/download/v0.0.2/hg-cli_0.0.2_linux_amd64.tar.gz"
        sha256 "6aa4a8bc7be3f9391fd924a29ab6ae0b75076dff65ceb2d45a493f5b05850dd9"

        def install
          bin.install "hg-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hostedgraphite/hg-cli/releases/download/v0.0.2/hg-cli_0.0.2_linux_arm64.tar.gz"
        sha256 "c3c6dd81736f87d187534401852f1fcb8c640cc74cb18f177094d7393b8d030e"

        def install
          bin.install "hg-cli"
        end
      end
    end
  end
end
