# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HgCli < Formula
  desc ""
  homepage "https://github.com/hostedgraphite/homebrew-hgcli"
  version "0.2.0-beta.1"

  on_macos do
    url "https://github.com/hostedgraphite/hg-cli/releases/download/v0.2.0-beta.1/hg-cli_0.2.0-beta.1_darwin_all.tar.gz"
    sha256 "678d5454bbf57df2cffd1f75ff8d9e40a4d6fe5f2ea51ec91f609642e05dab93"

    def install
      bin.install "hg-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hostedgraphite/hg-cli/releases/download/v0.2.0-beta.1/hg-cli_0.2.0-beta.1_linux_amd64.tar.gz"
        sha256 "1f8527666c41c41455dbee028b4271ac7e5534465ae9257eadf87f8139520335"

        def install
          bin.install "hg-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hostedgraphite/hg-cli/releases/download/v0.2.0-beta.1/hg-cli_0.2.0-beta.1_linux_arm64.tar.gz"
        sha256 "4dc594e40c71b21aeb30d1a1e33061676c1c84fadb4e91a4999dab1e47f3356c"

        def install
          bin.install "hg-cli"
        end
      end
    end
  end
end
