# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HgCli < Formula
  desc ""
  homepage "https://github.com/hostedgraphite/homebrew-hgcli"
  version "0.0.1-alpha"

  on_macos do
    url "https://github.com/hostedgraphite/hg-cli/releases/download/v0.0.1-alpha/hg-cli_0.0.1-alpha_darwin_all.tar.gz"
    sha256 "38d69ec9c12e056f5019709e9f9e81e917f694e700bf9c5fb09d958196b08b96"

    def install
      bin.install "hg-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hostedgraphite/hg-cli/releases/download/v0.0.1-alpha/hg-cli_0.0.1-alpha_linux_amd64.tar.gz"
        sha256 "53ae2872b83984e5dbb22b896b985641bd4826847f69317550ca5f1ae43dab03"

        def install
          bin.install "hg-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hostedgraphite/hg-cli/releases/download/v0.0.1-alpha/hg-cli_0.0.1-alpha_linux_arm64.tar.gz"
        sha256 "3209b0ef14b1aec2fd99396c1e46499b88354b484377537201712f88efd5f356"

        def install
          bin.install "hg-cli"
        end
      end
    end
  end
end
